### ISSUE TITLE
have some problems:

### ISSUE THREAD

**Issue by vision-heng** [ngunsu/matlab-eoh-sift#1]
error use siftrefinemx
All dimensions of DOG must be not less than 3.

error sift (line 274)
  oframes = siftrefinemx(...

error EOHSIFT_DEMO (line 83)
[frames1SIFT,descr1SIFT,gss1SIFT,dogss1SIFT]=sift( I1, 'Verbosity', 0 ) ;

who can help me ?

**Comment by vision-heng** [comment]
![image](https://user-images.githubusercontent.com/55314052/99075219-146f0480-25f4-11eb-95f7-38f58f3e74eb.png)
Who can help me？

**Comment by ngunsu** [comment]
I did this project almost five years ago. Currently, I don't even have Matlab so it's impossible for me to help you. Sorry
